### ISSUE TITLE
Machine Polish - Review Before GCC2018

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#104]
### Must Fix Bugs

- [ ] Tool shed installs broken - https://github.com/galaxyproject/planemo/issues/742.

### TODO

- [ ] Update samtools on the machine - the Planemo docs are complicated a bit because they expect a very old version of samtools - xref https://github.com/galaxyproject/planemo/pull/697.

### Older Items to Consider:

- [ ] Install bioblend-tutorial and place link on Desktop - https://github.com/nsoranzo/bioblend-tutorial (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] ensure docker images for IEs are pulled (maybe... -John)
- [ ] add env var $GALAXY_ROOT or update documentation to use $GALAXY 
- [ ] Install galaxy-parsec.
- [ ] Update ansible in the machine.
- [ ] ensure that the tool_conf.xml is writable.
    - fewer levels of indirection here? There is a non-sample tool_conf.xml, but the real tool_conf is "dev_tool_conf.xml" which loads tools from a folder, it is very complex...
