### ISSUE TITLE
Machine Polish (hopefully pre-GCC 2016)

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#43]
Ordered by importance (by Martin)
## Nice to have
- [ ] link to the galaxy log on the desktop of the virtual machine. (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] Turn off Terminal scrollback limits. (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] Turn off Terminal scroll on update. (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] change font size for terminal (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] Do you have to restart galaxy to see the tool? Hot load? (This is a bug - those tools should definitely show up.)
- [ ] missing  creation of a tool_dependencies.xml file which would be required for the seqkt and bwa tools to actually work if downloaded from the toolshed (place in planemo maybe?)
- [ ] disable screen saver
- [ ] Nginx should not say "forbidden" while starting up - it should say "Galaxy is unavailable - it may be starting..." (https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/nginx.conf.j2)
- [ ] change prompt (maybe just cwd, rather than default whole path ubuntu uses) (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [ ] enable IEs in default config (https://github.com/galaxyproject/planemo-machine/blob/master/group_vars/all#L115)
- [ ] ensure docker images for IEs are pulled (maybe... -John)
- [ ] npm install proxy stuff (This is probably done by ansible-galaxy-extras now? https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/defaults/main.yml#L158 - might have to witch defaults to enable it)
- [ ] Install bioblend-tutorial and place link on Desktop - https://github.com/nsoranzo/bioblend-tutorial  (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
## Already Has
- [x] 🔥 🔥 rebuild the image with the latest addition of komodo
- [x] Atom does not start https://github.com/galaxyproject/planemo-machine/issues/73
- [x] remove link to Atom from the desktop (since it is not used anymore) (should be fixed by https://github.com/galaxyproject/planemo-machine/pull/81)
- [x] 🔥   fix miniconda on the .ova image https://github.com/galaxyproject/planemo-machine/issues/78
- [x] :fire: add link to komodo-edit to the desktop (should be fixed by https://github.com/galaxyproject/planemo-machine/pull/81)
- [x] problem with `tool_init` in appliance tutorial (https://github.com/galaxyproject/planemo-machine/issues/74)
- [x] provide TS bootstrapping in virt appliance (https://github.com/galaxyproject/planemo-machine/issues/76)
- [x] set of default keyboards (#70?) (en_US, en_GB, de)
- [x] less default cpus and more vram https://github.com/galaxyproject/planemo-machine/pull/72
- [x] Document clipboard use in documentation. (https://github.com/galaxyproject/planemo/tree/master/docs)
- [x] Devbox role should `apt-get update` before completion to eliminate warnings about new packages. (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [x] Xubuntu profile should turn new package warning off altogether also. (#62) (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [x] provide a `$GALAXY_ROOT` (or `$GALAXY`) , so we can use that in docs and it'll work. E.g "Please cd to $GALAXY/lib/web/proxy/..." (#70) (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)
- [x] Move OVA docs first in appliance list. (https://github.com/galaxyproject/planemo/tree/master/docs)
- [x] Upgrade planemo (I think this would be covered with continuous building and testing).
- [x] Install google chrome. (#62) (https://github.com/galaxyproject/planemo-machine/blob/master/roles/galaxyprojectdotorg.devbox/tasks/main.yml)

**Comment by martenson** [comment]
Added feedback from https://github.com/galaxyproject/planemo/issues/241#issuecomment-119599552 via @Christian-B
Also removed the bug label. Muhehe.

**Comment by nsoranzo** [comment]
I'd also add: consolidate the 2 images (GCC2015-i386.ova and planemo) into 1.

**Comment by hexylena** [comment]
@martenson it's totally a bug :P

**Comment by hexylena** [comment]
@nsoranzo definitely

**Comment by davebx** [comment]
I'll be working my way through the list of issues per @jmchilton's request.

**Comment by jmchilton** [comment]
@davebx A million thanks - beer debt plus 4 or 5 - I'll go through and a little implementation note to some those then to at least point where I'd start looking at those if it were me.

**Comment by davebx** [comment]
Awesome, @jmchilton. All help gaining context is appreciated.

**Comment by bgruening** [comment]
@davebx I started to work on this as well. Here are my recent updates: https://github.com/galaxyproject/planemo-machine/compare/updates?expand=1

**Comment by martenson** [comment]
maybe disable screen saver?

**Comment by martenson** [comment]
the .ova image has the folllowing problems:
- video memory is set to 8MB which makes the rendering of the UI troublesome, especially when trying to work fullscreen - more reasonable default would be 32MB
- number of processors is set to 4 (which gives warning unless you have 4 physical processors on host)-  I changed it to 1 and have no problems

**Comment by nsoranzo** [comment]
@martenson: +1, I had the same issues

**Comment by martenson** [comment]
cpus and vram should be addressed by https://github.com/galaxyproject/planemo-machine/pull/72

**Comment by martenson** [comment]
I modified the first comment and reordered it, I think we need to polish a bit more and we don't have much time.

**Comment by martenson** [comment]
the tool_init and TS bootstrapping are resolved, however Atom still does not start and Conda does not have `write permissions in: /opt/miniconda` (https://github.com/galaxyproject/planemo-machine/issues/78)

ping @jmchilton @davebx

**Comment by jmchilton** [comment]
I like the emoji - thanks!

Is there a workaround at runtime for the atom problem? Does it work from the CLI?

**Comment by martenson** [comment]
@jmchilton I was not able to start atom in any way. When I installed miniconda manually it works fine so there is that. We really need an editor though, I tried installing sublime-text from the unofficial apt-get repo but that is also broken. gedit?

**Comment by jmchilton** [comment]
@martenson This worked before :frowning:.

Can you try `sudo apt-get install xubuntu-desktop` and see if that re-enables it?

If not, `sudo apt-get install kate`?

My guess is that https://github.com/galaxyproject/planemo-machine/pull/69/files broke this.

**Comment by martenson** [comment]
@jmchilton on it, will take a while since @comcast sucks

**Comment by martenson** [comment]
@jmchilton `sudo apt-get install xubuntu-desktop` does not help Atom (It might need to be present during installation? However when I uninstall and install it again it behaves the same :poop:)

kate installs and works fine...

**Comment by martenson** [comment]
komodo-edit also works and I consider it superior to kate

```
sudo add-apt-repository ppa:mystic-mirage/komodo-edit
sudo apt-get update
sudo apt-get install komodo-edit
```

![screenshot 2016-06-22 20 06 01](https://cloud.githubusercontent.com/assets/1814954/16287909/d0f9afce-38b4-11e6-9551-226258c23114.png)

**Comment by martenson** [comment]
I am rebuilding the machine to test komodo installation now

**Comment by jmchilton** [comment]
Thanks for testing - that looks like a great option.

**Comment by martenson** [comment]
@jmchilton ha, can't build shit cos can't install packer cos can't install mercurial cos `curl: (6) Could not resolve host: mercurial.selenic.com` 😆

**Comment by martenson** [comment]
Well I overcame that but hit another problem: https://github.com/Homebrew/homebrew-core/issues/2325

In the meantime I am building the machine on my machine.

**Comment by jmchilton** [comment]
I am going to close this out now - and I have opened a new issue for 2017 #85 . Hopefully the image holds up tomorrow. I really appreciate all the effort that went into making the 2016 image - a huge thanks to @martenson, @bgruening, and @davebx!
