### ISSUE TITLE
Create a pre-GCC manual testing checklist to apply every year.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo-machine#99]
- [ ] Check Docker is running with `docker ps`. (VM Planemo machine Only)
- [ ] Check other services with `sudo /usr/bin/check-planemo-machine.sh`.
- [ ] Click Galaxy link on Desktop.
  - [ ] Upload a file, verify it turns green.
  - [ ] Check IEs work.
- [ ] Check tool auto loading.
  - [ ] `cd /opt/galaxy/tools; planemo project_init --template demo .`
  - [ ] Open Galaxy link on Desktop and verify new concatenate and random lines tools show up.
- [ ] Walk through Planemo docs - relevant sections for tutorials giving.
  - [ ] Intro.
  - [ ] Advanced.
  - [ ] Conda Exercises
  - [ ] Container Exercises
